version: '2'
services:
    ilja-app:
        image: ilja
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ilja-postgresql:5432/ilja
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ilja-postgresql:
        extends:
            file: postgresql.yml
            service: ilja-postgresql
