version: '2'
services:
    ilja-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/ilja/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=vlasotince
        ports:
            - 5432:5432
